config/routes.rb
Rails.application.routes.draw do
  namespace :users do
    resources :account,  only: :index
    resources :profile,  only: [:edit, :update]
  end
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  devise_for :users
  root to: "top#index"
  resources :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one_attached :image
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception
    before_action :configure_permitted_parameters, if: :devise_controller?
  
    protected
  
    def configure_permitted_parameters
      added_attrs = [ :email, :username, :password, :password_confirmation ]
      devise_parameter_sanitizer.permit :sign_up, keys: added_attrs
      devise_parameter_sanitizer.permit :account_update, keys: added_attrs
      devise_parameter_sanitizer.permit :sign_in, keys: added_attrs
    end
end

app/controllers/top_controller.rb
class TopController < ApplicationController
  def index
  end
end

app/controllers/users/account_controller.rb
class Users::AccountController < ApplicationController
  def index
  end
end

app/controllers/users/profile_controller.rb
class Users::ProfileController < ApplicationController
  def edit
    @user = User.find(params[:id])
  end

  def update
    if @user.update(user_params)
      redirect_to @user
    else
      render :edit
    end
  end

  private
    def user_params
      params.require(:user).permit(:namename, :introduction, :image)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/helpers/users/account_helper.rb
module Users::AccountHelper
end

app/helpers/users/profile_helper.rb
module Users::ProfileHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ShareApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header class="header">
      <div class="header-inner">
        <div class="header-left-nav">
          <%= link_to image_tag("logo.png"), "/" %>
          <form action="https://presite-potepancamp-rails-02.herokuapp.com/rooms/search" accept-charset="UTF-8" method="get">
            <div class="header-sharch d-lg-inline-block d-none">
              <input type="text" name="area" id="area" value="" class="form-control" placeholder="エリア">
              <i class="fas fa-map-marker-alt"></i>
            </div>
            <div class="header-sharch d-lg-inline-block d-none">
              <input type="text" name="keyword" id="keyword" value="" class="form-control" placeholder="キーワード">
              <i class="fas fa-search"></i>
            </div>
            <input type="submit" name="commit" value="" class="d-none" data-disable-with="">
          </form>
        </div>
        <div class="header-right-nav">
          <% if user_signed_in? %>
            <div class="nav-item d-sm-inline-block d-none">
              <%= current_user.username %>
            </div>
            <div class="nav-item">
            <img class="mx-3 p-1 host-icon nav-trigger" alt="メニュー" >
              <ul class="header-nav-menu">
                <li><a>ルーム登録</a></li>
                <li><a>予約済みルーム一覧</a></li>
                <li><a>登録済みルーム一覧</a></li>
                <li><%= link_to "設定", users_account_index_path %></li>
                <li><%= link_to "ログアウト", destroy_user_session_path,　method: :delete %></li>
              </ul>
            </div>
            <% else %>
            <div class="nav-item">
              <%= link_to "ログイン", new_user_session_path, class: "btn btn-primary my-2 mx-3" %>
              <%= link_to "新規登録", new_user_registration_path, class: "btn btn-secondary" %>
            </div>
          <% end %>
        </div>
      </div>
    </header>
    
    <div class="clearfix"></div>
    
    <script>
      $(function() {
        $('.nav-trigger').click(function() {
          $('.header-nav-menu').toggle(1500);
        })
      });
    </script>

    <% if flash[:notice] %>
      <div class="notifications">
        <div class="notice"><%= notice %></div>
      </div>
    <% end %>
    <% if flash[:alert] %>
      <div class="notifications">
        <div class="alert"><%= alert %></div>
      </div>
    <% end %>

    <%= yield %>

    <footer class="footer">
      <p>© 2020 POTEPAN.INC.</p>
    </footer>

  </body>
</html>

app/views/top/index.html.erb
<div class="top">
  <div class="top-main">
    <div class="container">
      <div class="row col-lg-6">
        <div class="form-fream">
          <div class="form-area">
            <p class="form-area-title mb-4">Potepan Shareでまだ体験したことのない旅をしよう</p>
            <form action="https://presite-potepancamp-rails-02.herokuapp.com/rooms/search" accept-charset="UTF-8" method="get">
              <label for="___">エリア</label>
              <input type="text" name="area" id="area" value="" class="form-control mb-4" placeholder="東京">
              <input type="submit" name="commit" value="探す" class="form-control btn-primary mb-4" data-disable-with="探す">
            </form>                    
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="container">
    <div class="panel-area m-5">
      <h1 class="section-title">おすすめのエリア</h1>
      <div class="row">
        <div class="panel-item col-lg-3 col-6">
          <span>東京</span>
          <a href="https://presite-potepancamp-rails-02.herokuapp.com/rooms/search?area=%E6%9D%B1%E4%BA%AC"><img class="panel-image" src="/assets/img_tokyo.jpg"></a>
          <div class="shadow"></div>
        </div>
        <div class="panel-item col-lg-3 col-6">
          <span>大阪</span>
          <a href="https://presite-potepancamp-rails-02.herokuapp.com/rooms/search?area=%E5%A4%A7%E9%98%AA"><img class="panel-image" src="/assets/img_osaka.jpg"></a>
          <div class="shadow"></div>
        </div>
        <div class="panel-item col-lg-3 col-6">
          <span>京都</span>
          <a href="https://presite-potepancamp-rails-02.herokuapp.com/rooms/search?area=%E4%BA%AC%E9%83%BD"><img class="panel-image shadow" src="/assets/img_kyoto.jpg"></a>
          <div class="shadow"></div>
        </div>
        <div class="panel-item col-lg-3 col-6">
          <span>札幌</span>
          <a href="https://presite-potepancamp-rails-02.herokuapp.com/rooms/search?area=%E6%9C%AD%E5%B9%8C"><img class="panel-image" src="/assets/img_sapporo.jpg"></a>
          <div class="shadow"></div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/users/account/index.html.erb
<div class="container-fiuld user"> 
  <div class="row">
    <div class="col-lg-2 user-nav user-nav-pc d-lg-block d-none">
      <ul>
        <li class="active"><%= link_to "アカウント", users_account_index_path %></li>
        <li class=""><%= link_to "プロフィール", edit_users_profile_path(current_user) %></li>
      </ul>
    </div>
    <div class="col-lg-2 user-nav user-nav-mobile d-lg-none">
      <ul>
        <li class="active"><%= link_to "アカウント", users_account_index_path %></li>
        <li class=""><%= link_to "プロフィール", edit_users_profile_path(current_user) %></li>
      </ul>
    </div>
    <div class="col-md-10 user-view">
      <div class="user-view-box">
        <div class="update-content">
          <div class="row">
            <h5>アカウント</h5>
          </div>
        </div>
        <div class="update-content">
          <div class="row">
            <label class="col-md-3" for="email">メールアドレス</label>
            <div class="col-md-9"><%= current_user.email %></div>
          </div>
        </div>
        <div class="update-content">
          <div class="row">
            <label class="col-md-3" for="password">パスワード</label>
            <div class="col-md-9"><%= current_user.password %>********</div>
          </div>
        </div>
        <div class="update-content">
          <div class="row">
            <%= link_to "編集", edit_user_registration_path, class: "col-md-2 btn btn-primary mx-3" %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/users/profile/edit.html.erb
<div class="container-fiuld user">
  <div class="row">
    <div class="col-lg-2 user-nav user-nav-pc d-lg-block d-none">
      <ul>
        <li class=""><%= link_to "アカウント", users_account_index_path %></li>
        <li class="active"><%= link_to "プロフィール", edit_users_profile_path(current_user) %></li>
      </ul>
    </div>
    <div class="col-lg-2 user-nav user-nav-mobile d-lg-none">
      <ul>
        <li class=""><%= link_to "アカウント", users_account_index_path %></li>
        <li class="active"><%= link_to "プロフィール", edit_users_profile_path(current_user) %></li>
      </ul>
    </div>
    <div class="col-lg-10 user-view">
      <div class="user-view-box">
        <div class="update-content">
          <div class="row">
            <h5>プロフィール</h5>
          </div>
        </div>
        <%= form_with model: @user, url: users_profile_path do |f| %>
          <div class="update-content">
            <div class="row">
              <div class="col-md-6 offset-md-3">
                <div class="icon-box">
                  <% if @user.image.attached? %>
                    <%= image_tag @user.image, class: "icon-image host-icon" %>
                  <% else %>
                    <img alt="アイコン画像" class="icon-image host-icon">
                  <% end %>
                </div>
              </div>
            </div>
          </div>
          <div class="update-content">
            <div class="row">
              <%= f.label :avatar, "アイコン画像", class: "col-md-3 required-a" %>
              <%= f.file_field class: "mb-4 col-md-9", placeholder: "アイコン画像をアップロード" %>
            </div>
          </div>
          <div class="update-content">
            <div class="row">
              <%= f.label :username, "名前", class: "col-md-3 required-a" %>
              <%= f.text_field :username, class: "mb-4 col-md-9", placeholder: "名前を入力" %>
            </div>
          </div>
          <div class="update-content">
            <div class="row">
              <%= f.label :profile, "自己紹介", class: "col-md-3 required-a" %>
              <%= f.text_area :profile, class: "form-control mb-4 col-md-9", placeholder: "自己紹介を入力" %>
            </div>
          </div>
          <div class="update-content">
            <div class="row">
              <%= f.submit "更新", class:"col-md-2 btn btn-primary mx-3" %>
            </div>
          </div>
        <% end %>       
      </div>
    </div>
  </div>
</div>

app/views/users/profile/update.html.erb
<h1>Users::Profile#update</h1>
<p>Find me in app/views/users/profile/update.html.erb</p>